spring.application.name=app
app.frontend.url=http://localhost:3000

# MOMO PAYMENT CONFIGURATION (SANDBOX)
momo.partner-code=MOMOBKUN20180529
momo.access-key=klm05nu90q1khu6D
momo.secret-key=at67qH6mk8w5Y1n71ytr474Y7otE69u4
momo.api-url=https://test-payment.momo.vn/v2/gateway/api/create
momo.return-url=http://localhost:8080/api/payment/momo/return
momo.notify-url=http://localhost:8080/api/payment/momo/ipn
